name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    container:
      image: rocker/r2u:latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: apt update -qq && apt install -y curl jq git
    - name: Setup environment
      run: ./setup.sh
    - name: Evaluation (development)
      id: evaluate-dev
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: evaluate-dev
        command: ./evaluate.sh
        timeout: 10
    - name: Evaluation (production)
      id: evaluate-prod
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: evaluate-prod
        command: ./production.sh ${{ secrets.PROD_KEY }}
        timeout: 10
    - name: Report results
      run: |
        json_dev="evaluate.json"
        json_prod="prod/evaluate.json"
        echo "Development:"
        jq . $json_dev
        echo "Production:"
        jq . $json_prod
        pass_dev="$(jq .grade.pass[0] $json_dev)
        total_dev=$(jq .grade.total[0] $json_dev)
        echo "Development score: $pass_dev / $total_dev"
        pass_prod="$(jq .grade.pass[0] $json_prod)
        total_prod=$(jq .grade.total[0] $json_prod)
        echo "Production score: $pass_prod / $total_prod"
        pass=$(( pass_dev + 2 * pass_prod ))
        total=$(( total_dev + 2 * total_prod ))
        echo "::notice title=Autograding complete::Points ${pass}/${total}"
        echo "::notice title=Autograding report::{\"totalPoints\":${pass},\"maxPoints\":${total}}"
