name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup R
      run: apt-get install -y r-base r-cran-digest
    - name: evaluate-dev
      id: evaluate-dev
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: evaluate-dev
        setup-command: "./setup.sh"
        command: "./evaluate-dev.sh"
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        EVALUATE-DEV_RESULTS: "${{steps.evaluate-dev.outputs.result}}"
      with:
        runners: evaluate-dev
