name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    container:
      image: rocker/r2u:latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: apt update -qq && apt install -y curl jq git
    - name: Setup environment
      run: ./setup.sh
    - name: Evaluation (development)
      id: evaluate-dev
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: evaluate-dev
        command: ./evaluate.sh
        timeout: 10
    - name: Evaluation (production)
      id: evaluate-prod
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: evaluate-prod
        command: ./production.sh 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
        timeout: 10
    - name: Report results
      run: ./report.sh
